defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 8

development:
  database: weatherrooster_development

test:
  database: weatherrooster_test

production:
  database: weatherrooster_production
